# Generated by Django 3.1.3 on 2020-11-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYNEWAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customer_details'},
        ),
    ]
