# Generated by Django 3.1.3 on 2020-11-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYNEWAPP', '0002_auto_20201105_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=23)),
                ('favorite_fruit', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'student_details',
            },
        ),
    ]
