# Generated by Django 3.1.3 on 2020-11-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYNEWAPP', '0003_studentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playerdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('Allrounder', 'Allrounder')], max_length=25)),
                ('COUNTRY', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'playerdetails',
            },
        ),
    ]
