# Generated by Django 3.1.3 on 2020-11-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYNEWAPP', '0004_playerdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerdetails',
            options={'verbose_name_plural': 'player_details'},
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='confirmpassword',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='email',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='password',
            field=models.CharField(default='NA', max_length=25),
        ),
    ]
