# Generated by Django 3.1.3 on 2020-11-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYNEWAPP', '0006_auto_20201111_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetails',
            name='address',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='playerdetails',
            name='email',
            field=models.TextField(default='NA'),
        ),
    ]
