# Generated by Django 3.1.3 on 2020-11-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYNEWAPP', '0007_auto_20201111_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetails',
            name='fileupload',
            field=models.FileField(default='NA', upload_to='documents'),
        ),
    ]
