# Generated by Django 3.1.2 on 2020-11-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYNEWAPP', '0008_playerdetails_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
